{% set version = "20251122" %}
{% set sha256 = "368d1982cfd9dbebb8cd0e444de6199559df94ac2dd1edf95f74350f0af1e84d" %}

package:
  name: parallel
  version: {{ version }}

source:
  url: https://ftpmirror.gnu.org/parallel/parallel-{{ version }}.tar.bz2
  fn: parallel-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  build:
    - make
    - m2-make  # [win]
    - m2-grep  # [win]
    - m2-gawk  # [win]
  run:
    - perl

test:
  commands:
    - parallel --version  # [not win]
    - bash -c 'export SHELL=`cygpath -u "$BASH"`; parallel --plain --version'  # [win]

about:
  home: http://www.gnu.org/software/parallel/
  license: CC-BY-SA-4.0 AND GFDL-1.3-or-later AND GPL-3.0-or-later
  license_family: GPL
  summary: GNU parallel is a shell tool for executing jobs in parallel using one or more computers.
  license_file:
    - LICENSES/CC-BY-SA-4.0.txt
    - LICENSES/GFDL-1.3-or-later.txt
    - LICENSES/GPL-3.0-or-later.txt

extra:
  recipe-maintainers:
    - rvalieris
