{% set version = "20190522" %}
{% set sha256 = "5bc60a65902102eb080690cd4cf168bc99f74a467ee9c7ff98ea0dbd3c4f7f78" %}

package:
  name: parallel
  version: {{ version }}

source:
  url: http://ftpmirror.gnu.org/parallel/parallel-{{ version }}.tar.bz2
  fn: parallel-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  # [win]

requirements:
  run:
    - perl
  
test:
  commands:
    - parallel --version

about:
  home: http://www.gnu.org/software/parallel/
  license: GPL-3
  license_family: GPL
  summary: GNU parallel is a shell tool for executing jobs in parallel using one or more computers.
  license_file: COPYING

extra:
  recipe-maintainers:
    - rvalieris
