{% set version = "20221122" %}
{% set sha256 = "aa3d9d22434df148d693f1a6232331a126729b6a22d2f7261b17fba9ad99539d" %}

package:
  name: parallel
  version: {{ version }}

source:
  url: http://ftpmirror.gnu.org/parallel/parallel-{{ version }}.tar.bz2
  fn: parallel-{{ version }}.tar.bz2
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - make
    - m2-make  # [win]
    - m2-grep  # [win]
    - m2-gawk  # [win]
  run:
    - perl

test:
  commands:
    - parallel --version  # [not win]
    - bash -c 'export SHELL=`cygpath -u "$BASH"`; parallel --plain --version'  # [win]

about:
  home: http://www.gnu.org/software/parallel/
  license: GPL-3
  license_family: GPL
  summary: GNU parallel is a shell tool for executing jobs in parallel using one or more computers.
  license_file: LICENSES/GPL-3.0-or-later.txt

extra:
  recipe-maintainers:
    - rvalieris
