travis:
  secure:
    BINSTAR_TOKEN: JLOsEhtOjKDdMggqvlVcW1xp0D6ji82/0vFgElbc3TgUE/qSQvK33BwizG1UahjBkQWwQR6rKZbAbfnZTsjVkMP+KRm2StZR3ULLAeOvae2Rkl70IjYV3IviPu6+2NxLDePT+OmpT4600dJXlu0xQGrThKegl6XwqedlIJcskkBCrQuBwJgCTVgt9Q7XP5hymtiyQgKs7n2N1qMgC71j7KHzlUe3McFSRwFPF+2ZlEmjch7/UlacOK1m7PzE4mQkFeO/rCVgS6JIhRFvv9TjShX8eJ4UFDaLWHsg4UKdApS4ourCiC3i+Hns/KrAymsWptPcHItZf7LKHFBsw7Zqp7q6o3wFhByeQmbWp7hmAgzQJU5V8PqW0Vh1IlKV8ufdPSXA0saBleVF7I8/Uau7kZV93Op11wIJYGNPP34nbLagI81uDCrSfTOsWZBCyTRIvwD6mT4Qi5ajEd4TC36VfzIBzsUcg9muIUym7mvJ6R9jMujLbH1yZYLuLdAzsEpLwJDQTV8XgEOFA5jRqLODVbGTQdIP5jgy1DPPaZvRl0v03owU5lx6JdnJ5I9EulFFJXvMUgNPqqUwil1Yc1dpih5e9dFmDPj++FQTHInXxuRfYCX++HGFlANsQPgdkDztFHOj/8cU8wGe4XbCkidFUdopkqMC7PS0FQCAVpZmcWI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
