travis:
  secure:
    BINSTAR_TOKEN: CymnkLnlNgYMLAuP0wu4gEdvEhcy3Qw4LdtnDPevvciVV7OcKveQpfpBk2GpZBZVBDRDkc3C60+L94vYjtArlRDvS6xcZ09kfaPL4d05MRDcTTkoXbeYAtj/wDiktByKNrEk2y2VXZsLAZ9Ybw6H8G2pnDX18jUb5JThlCy10fB5+aU+6BpixL1FOpZv2CFxPInweYRHwXfAipk2/SsXC4yAUgjja83VySwqnc6zCmWdayqyl9D/noIhskZiHj5DH39buDreHhmJSeLK1Mz8YMSlgAuNLAOuYsKZWTuGqwHlXGwb5lsGrh385U3Is71zTDXz35a/Ljez8XbgNmzzzhc/wi7orPiYSdSQc8HLEVkBRrF7m6uyXprA5HYl9CjcDnzGQhROF7CIi3M6zhAl0ls3VyZ9SH1Sx0VKyZMuZ3zf1m2NymRKPeD1KEVVjBsDAftdaJrTPKH2JOJnytYDHnR8wJDN2uoNBjBL3YvTaq0yQXXcfkz++blznwFqgP9ZtREyew8Nbyn1d/OTZkS7cm9HzBbG0XqnYqIMSjh5C6maDFBqX4+0Zta2iOTQ4hLG09NbDUFW8JykviAXTxsa1ClXSZ+B8VtOcdH2jqc0ZC05G41HdA/F3Um3JgrKm+7uG6WRdNnUfUEDDtQ3yODdc+Dx2IbC98iQj3s73Dle1F4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
